In [1]:
def load_data(path, test=False):
    lines = []
    with open(path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        lines = [l.strip() for l in lines]
    if test:
        ids = [l.split(',')[0] for l in lines]
        return ids, lines
    else:
        return lines

In [2]:
pos = load_data('data/train_pos.txt')
neg = load_data('data/train_neg.txt')

In [3]:
import string

def clean(tweet):
    lower = tweet.lower()
    no_user_token = lower.replace('<user>', '')
    no_token = no_user_token.replace('<url>', '')
    no_punct = no_token.translate(str.maketrans('', '', string.punctuation))
    no_digit = [w for w in no_punct.split() if not w.isdigit()]
    return no_digit

In [4]:
clean_pos = [clean(t) for t in pos]
clean_neg = [clean(t) for t in neg]

In [5]:
from nltk.stem.wordnet import WordNetLemmatizer


import nltk
nltk.download('wordnet')

def lemmatize(words):
    lem = WordNetLemmatizer()
    verbs = [lem.lemmatize(w, 'v') for w in words] # verbs
    return [lem.lemmatize(w, 'n') for w in verbs] # nouns

[nltk_data] Downloading package wordnet to /home/anton/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [6]:
lemmatized_pos = [lemmatize(w) for w in clean_pos]
lemmatized_neg = [lemmatize(w) for w in clean_neg]

In [7]:
def save_cleaned(path, data, isPos):
    label = "-1"
    if isPos :
        label = "1"
    with open(path, 'w', encoding='utf-8') as f:
        for words in data:
            f.write(' '.join(words) + " , " + label)
            f.write('\n')
            
def append_cleaned(path, data, isPos):
    label = "0"
    if isPos :
        label = "1"
    with open(path, 'a', encoding='utf-8') as f:
        for words in data:
            mot = ' '.join(words)
            if mot != "":
                f.write(mot + " , " + label)
                f.write('\n')

In [8]:
!rm data/clean_train.txt

In [9]:
save_cleaned('data/clean_train_pos.txt', lemmatized_pos, True)
save_cleaned('data/clean_train_neg.txt', lemmatized_neg, False)


append_cleaned('data/clean_train.txt', lemmatized_pos, True)
append_cleaned('data/clean_train.txt', lemmatized_neg, False)

-----------------------------------------------

In [9]:
from collections import Counter
counter_lem_pos = Counter()
counter_lem = Counter()
for t in lemmatized_pos:
    for w in t:
        counter_lem_pos[w]+=1
        counter_lem[w]+=1
counter_lem_neg = Counter()
for t in lemmatized_neg:
    for w in t:
        counter_lem_neg[w]+=1
        counter_lem[w]+=1

In [12]:
clean_lem_counter = {x : counter_lem[x] for x in counter_lem if counter_lem[x] > 50}
len(clean_lem_counter)

3330

In [13]:
# most common in both
thresh = 100
most_common_pos = [w for w,c in counter_lem_pos.most_common()[:thresh]]
most_common_neg = [w for w,c in counter_lem_neg.most_common()[:thresh]]

In [14]:
most_common_in_both = []
for w in most_common_pos:
    if w in most_common_neg:
        most_common_in_both.append(w)
#most_common_in_both

In [15]:
# remove most common in both
clean_lem_counter_2 = counter_lem.copy()
for w in most_common_in_both:
    clean_lem_counter_2.pop(w)

In [16]:
# remove words that appear scarcely
thresh_2 = 50
chosen_words = [x for x in clean_lem_counter_2 if clean_lem_counter_2[x] > thresh_2]
len(chosen_words)

3255

In [17]:
# save words
with open('data/chosen_words.txt', 'w', encoding='utf-8') as f:
    for w in chosen_words:
        f.write(w + '\n')

---------------------------------------------------

In [47]:
import numpy as np
import random

training = np.genfromtxt('data/clean_train.txt', delimiter=' , ', dtype=None)

random.shuffle(training)

train_data = training[:140000]
test_data = training[140000:]


# create our training data from the tweets
train_x = [x[0] for x in train_data]
# index all the sentiment labels
train_y = np.asarray([x[1] for x in train_data])

test_x = [x[0] for x in test_data]

test_y = np.asarray([x[1] for x in test_data])


/home/anton/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


In [48]:
import json
import keras
import keras.preprocessing.text as kpt
from keras.preprocessing.text import Tokenizer

# only work with the 3000 most popular words found in our dataset
max_words = 3000

# create a new Tokenizer
tokenizer = Tokenizer(num_words=max_words)
# feed our tweets to the Tokenizer
tokenizer.fit_on_texts(train_x)

# Tokenizers come with a convenient list of words and IDs
dictionary = tokenizer.word_index
# Let's save this out so we can use it later
with open('dictionary.json', 'w') as dictionary_file:
    json.dump(dictionary, dictionary_file)


def convert_text_to_index_array(text):
    # one really important thing that `text_to_word_sequence` does
    # is make all texts the same length -- in this case, the length
    # of the longest text in the set.
    return [dictionary[word] for word in kpt.text_to_word_sequence(text)]

allWordIndices = []
# for each tweet, change each token to its ID in the Tokenizer's word_index
for text in train_x:
    wordIndices = convert_text_to_index_array(text)
    allWordIndices.append(wordIndices)

# now we have a list of all tweets converted to index arrays.
# cast as an array for future usage.
allWordIndices = np.asarray(allWordIndices)

# create one-hot matrices out of the indexed tweets
train_x = tokenizer.sequences_to_matrix(allWordIndices, mode='binary')
# treat the labels as categories
train_y = keras.utils.to_categorical(train_y, 2)

In [49]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation

model = Sequential()
model.add(Dense(512, input_shape=(max_words,), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(256, activation='sigmoid'))
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))

In [50]:
model.compile(loss='categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy'])

In [52]:
model.fit(train_x, train_y,
  batch_size=32,
  epochs=2,
  verbose=1,
  validation_split=0.1
)

Train on 126000 samples, validate on 14000 samples
Epoch 1/2
126000/126000 [==============================] - 70s 552us/step - loss: 0.0925 - accuracy: 0.9793 - val_loss: 0.6997 - val_accuracy: 0.8001
Epoch 2/2
126000/126000 [==============================] - 68s 537us/step - loss: 0.0737 - accuracy: 0.9820 - val_loss: 0.6926 - val_accuracy: 0.8066


In [53]:
model_json = model.to_json()
with open('model.json', 'w') as json_file:
    json_file.write(model_json)

model.save_weights('model.h5')

In [ ]:
import json
import numpy as np
import keras
import keras.preprocessing.text as kpt
from keras.preprocessing.text import Tokenizer
from keras.models import model_from_json

# we're still going to use a Tokenizer here, but we don't need to fit it
tokenizer = Tokenizer(num_words=3000)
# for human-friendly printing
labels = ['negative', 'positive']

# read in our saved dictionary
with open('dictionary.json', 'r') as dictionary_file:
    dictionary = json.load(dictionary_file)

# this utility makes sure that all the words in your input
# are registered in the dictionary
# before trying to turn them into a matrix.
def convert_text_to_index_array(text):
    words = kpt.text_to_word_sequence(text)
    wordIndices = []
    for word in words:
        if word in dictionary:
            wordIndices.append(dictionary[word] + 1)
        else:
            wordIndices.append(1)
            #print("'%s' not in training corpus; ignoring." %(word))
    return wordIndices

def predict(test_data):
    
    json_file = open('model.json', 'r')
    loaded_model_json = json_file.read()
    json_file.close()

    model = model_from_json(loaded_model_json)

    model.load_weights('model.h5')
    
    preds = []
    
    test_data = [' '.join(lemmatize(clean(w))) for w in test_data]
    
    for l in test_data:
        testArr = convert_text_to_index_array(l)
        input = tokenizer.sequences_to_matrix([testArr], mode='binary')
        
        pred = model.predict(input)
        print(pred)
        
        preds.append(np.argmax(pred))
    return preds

#test_ids, test_data = load_data('data/test_data.txt', test=True)
preds = predict(test_x)

[[0.00794091 0.9920591 ]]
[[0.00731731 0.99268275]]
[[0.00198052 0.99801946]]
[[0.00125712 0.9987429 ]]
[[0.00235111 0.9976489 ]]
[[0.00183214 0.9981679 ]]
[[0.10529619 0.8947038 ]]
[[0.00215735 0.99784267]]
[[8.6846744e-04 9.9913150e-01]]
[[0.07398175 0.9260183 ]]
[[0.00242816 0.9975719 ]]
[[0.00156185 0.9984382 ]]
[[0.04084443 0.9591556 ]]
[[0.8319194  0.16808066]]
[[0.01405821 0.9859418 ]]
[[0.04648447 0.9535155 ]]
[[0.00658965 0.9934103 ]]
[[0.00256555 0.99743444]]
[[0.00336264 0.99663734]]
[[0.00188588 0.9981141 ]]
[[0.01090446 0.9890955 ]]
[[0.00474783 0.99525213]]
[[0.15423287 0.84576714]]
[[0.00474185 0.99525815]]
[[0.0773844 0.9226156]]
[[0.00549505 0.994505  ]]
[[0.03479351 0.9652065 ]]
[[0.00633846 0.9936615 ]]
[[0.1480322 0.8519678]]
[[0.00186533 0.9981346 ]]
[[0.00500016 0.9949999 ]]
[[0.02193309 0.9780669 ]]
[[0.00288942 0.9971106 ]]
[[0.00791824 0.99208176]]
[[0.0018648 0.9981352]]
[[0.00261889 0.99738103]]
[[9.1880700e-04 9.9908113e-01]]
[[0.00534876 0.99465126]]
[[0.00

[[0.00386653 0.99613345]]
[[0.00178317 0.9982168 ]]
[[0.00163743 0.9983626 ]]
[[0.00317524 0.99682474]]
[[0.0027544  0.99724567]]
[[0.00150513 0.99849486]]
[[0.00135847 0.99864155]]
[[0.02895717 0.9710428 ]]
[[0.00107915 0.9989209 ]]
[[8.9106860e-04 9.9910897e-01]]
[[0.01197919 0.98802084]]
[[0.00128079 0.9987192 ]]
[[9.3461043e-04 9.9906546e-01]]
[[0.00197698 0.99802303]]
[[0.00486824 0.99513173]]
[[0.00365397 0.99634606]]
[[0.00435942 0.9956405 ]]
[[0.785195   0.21480502]]
[[0.14491174 0.85508835]]
[[0.12174413 0.87825584]]
[[0.0012889 0.9987111]]
[[0.00124201 0.99875796]]
[[0.00175196 0.9982481 ]]
[[0.00366398 0.996336  ]]
[[0.00172821 0.9982718 ]]
[[0.01330553 0.98669446]]
[[0.00107434 0.9989256 ]]
[[0.08820377 0.9117962 ]]
[[0.00146082 0.9985392 ]]
[[0.00179833 0.9982016 ]]
[[0.00236019 0.9976398 ]]
[[0.08083125 0.9191688 ]]
[[0.00239978 0.99760026]]
[[0.00150382 0.9984962 ]]
[[0.00196975 0.99803025]]
[[0.00161531 0.9983847 ]]
[[0.00450154 0.99549854]]
[[0.00113967 0.99886036]]
[[

[[0.0075142  0.99248576]]
[[0.00108033 0.9989197 ]]
[[0.00099966 0.9990004 ]]
[[0.00109722 0.9989028 ]]
[[0.04859449 0.9514055 ]]
[[0.00184837 0.9981516 ]]
[[0.00382996 0.99617   ]]
[[0.00157108 0.9984289 ]]
[[0.02138964 0.9786104 ]]
[[0.00139881 0.99860126]]
[[0.00196369 0.9980363 ]]
[[0.0133385 0.9866615]]
[[9.5788605e-04 9.9904209e-01]]
[[0.00645302 0.993547  ]]
[[0.1638154 0.8361846]]
[[0.00450154 0.99549854]]
[[0.07785629 0.92214376]]
[[0.00341738 0.9965827 ]]
[[0.00152381 0.9984762 ]]
[[0.00573431 0.99426574]]
[[0.00184921 0.99815077]]
[[0.00200257 0.99799746]]
[[0.00252139 0.99747866]]
[[0.0060938 0.9939062]]
[[0.03802305 0.9619769 ]]
[[0.03496031 0.96503973]]
[[0.00154793 0.99845207]]
[[0.0053652  0.99463487]]
[[0.00250878 0.99749124]]
[[0.00307884 0.9969212 ]]
[[0.00370756 0.9962924 ]]
[[0.00222463 0.9977754 ]]
[[0.00124581 0.99875414]]
[[0.00350081 0.9964992 ]]
[[0.00752345 0.9924765 ]]
[[0.05958289 0.9404171 ]]
[[0.00170116 0.9982988 ]]
[[0.09126231 0.9087377 ]]
[[0.00235731

[[0.00905445 0.9909456 ]]
[[0.36931708 0.63068295]]
[[0.00584373 0.99415624]]
[[0.00209892 0.9979011 ]]
[[0.0045462  0.99545383]]
[[0.10325652 0.8967434 ]]
[[0.02370958 0.97629035]]
[[0.01087588 0.98912406]]
[[0.0095036 0.9904964]]
[[0.00164281 0.9983571 ]]
[[0.00503134 0.9949687 ]]
[[0.06528413 0.9347159 ]]
[[0.00110598 0.99889404]]
[[0.01793912 0.9820609 ]]
[[0.00123635 0.9987637 ]]
[[0.07713611 0.92286396]]
[[0.00264533 0.99735475]]
[[0.00297783 0.9970222 ]]
[[0.0098905  0.99010956]]
[[0.00270684 0.9972932 ]]
[[0.00351541 0.99648464]]
[[8.629029e-04 9.991371e-01]]
[[0.01028279 0.98971725]]
[[0.02293138 0.9770686 ]]
[[0.0049281 0.9950718]]
[[0.00243412 0.99756587]]
[[0.00424176 0.99575824]]
[[0.04331575 0.95668423]]
[[9.323881e-04 9.990676e-01]]
[[0.0020562 0.9979438]]
[[0.00197606 0.998024  ]]
[[0.00379944 0.9962005 ]]
[[0.00468564 0.99531436]]
[[0.00297719 0.9970228 ]]
[[0.02063784 0.97936213]]
[[0.00243568 0.9975643 ]]
[[0.00239864 0.99760133]]
[[0.00408506 0.9959149 ]]
[[0.018561

[[0.00274483 0.99725515]]
[[0.00200558 0.9979944 ]]
[[0.05971742 0.9402826 ]]
[[0.00155745 0.9984426 ]]
[[0.12117925 0.8788208 ]]
[[0.00108766 0.99891233]]
[[0.01608028 0.9839197 ]]
[[0.11096937 0.8890307 ]]
[[9.905230e-04 9.990095e-01]]
[[0.00197615 0.99802387]]
[[0.00450154 0.99549854]]
[[0.03125782 0.9687422 ]]
[[6.8120199e-04 9.9931884e-01]]
[[0.00117611 0.9988238 ]]
[[0.00133401 0.99866605]]
[[0.13399836 0.86600167]]
[[0.00138797 0.99861205]]
[[0.00489763 0.9951024 ]]
[[0.00580077 0.9941993 ]]
[[0.00372267 0.9962773 ]]
[[0.00603652 0.9939634 ]]
[[0.01165571 0.9883443 ]]
[[0.07138529 0.92861474]]
[[0.04339834 0.9566016 ]]
[[0.0142062  0.98579377]]
[[0.00639949 0.9936005 ]]
[[0.00111359 0.9988864 ]]
[[9.8580669e-04 9.9901414e-01]]
[[0.00245671 0.99754333]]
[[0.00129885 0.9987011 ]]
[[0.00244903 0.997551  ]]
[[0.0018098 0.9981902]]
[[0.00577651 0.99422354]]
[[0.00451776 0.9954822 ]]
[[0.00119968 0.9988003 ]]
[[0.22047392 0.77952605]]
[[0.00127228 0.99872774]]
[[0.00238139 0.9976186 ]

[[9.4070629e-04 9.9905926e-01]]
[[0.00231996 0.99768   ]]
[[0.08397435 0.9160256 ]]
[[0.00370255 0.9962974 ]]
[[0.00115042 0.99884963]]
[[0.00513847 0.99486154]]
[[0.00484863 0.9951514 ]]
[[0.00630429 0.9936957 ]]
[[0.00223615 0.9977639 ]]
[[0.00187132 0.9981287 ]]
[[0.02859996 0.9714001 ]]
[[0.00490082 0.9950991 ]]
[[0.0022665 0.9977335]]
[[0.02033718 0.97966284]]
[[0.00242378 0.9975762 ]]
[[0.00275489 0.9972451 ]]
[[6.807454e-04 9.993193e-01]]
[[0.0036283  0.99637175]]
[[0.00790388 0.99209607]]
[[0.0032355  0.99676454]]
[[0.02199976 0.9780002 ]]
[[0.00127106 0.99872893]]
[[0.13723277 0.8627672 ]]
[[0.02315969 0.97684026]]
[[0.11192083 0.8880792 ]]
[[0.00189633 0.9981036 ]]
[[0.00396777 0.9960322 ]]
[[0.00381735 0.9961826 ]]
[[0.00867419 0.9913258 ]]
[[0.00107274 0.9989273 ]]
[[0.00212082 0.99787915]]
[[0.00362399 0.996376  ]]
[[0.00115897 0.9988411 ]]
[[0.00182134 0.9981787 ]]
[[0.00660117 0.9933988 ]]
[[0.01203005 0.98797   ]]
[[0.0138051  0.98619485]]
[[0.00523801 0.994762  ]]
[[0.

[[0.0744293  0.92557067]]
[[0.00150893 0.99849105]]
[[0.00256214 0.99743783]]
[[0.03342135 0.9665786 ]]
[[0.00269639 0.9973036 ]]
[[0.00217426 0.9978257 ]]
[[8.421783e-04 9.991578e-01]]
[[0.20299873 0.79700136]]
[[0.00509515 0.9949049 ]]
[[0.0332621  0.96673787]]
[[0.20232451 0.79767543]]
[[0.0670709  0.93292904]]
[[0.04881924 0.9511808 ]]
[[0.00318883 0.9968112 ]]
[[0.01794845 0.98205155]]
[[0.00146222 0.9985378 ]]
[[0.01397772 0.98602223]]
[[0.07430176 0.9256982 ]]
[[0.00374833 0.99625164]]
[[0.00890892 0.99109113]]
[[0.00527519 0.9947248 ]]
[[0.09767242 0.90232754]]
[[0.00179482 0.9982052 ]]
[[0.01142213 0.98857784]]
[[0.0017429 0.9982571]]
[[0.00121378 0.9987863 ]]
[[0.00136726 0.9986327 ]]
[[0.00448602 0.995514  ]]
[[0.00643091 0.993569  ]]
[[0.00503624 0.99496377]]
[[0.00211345 0.9978866 ]]
[[0.01272879 0.98727113]]
[[0.00125134 0.99874866]]
[[0.00966117 0.99033886]]
[[0.00853992 0.9914601 ]]
[[0.01924721 0.98075277]]
[[0.00486263 0.9951374 ]]
[[0.04920515 0.9507948 ]]
[[0.001365

[[0.00856212 0.99143785]]
[[0.00457314 0.9954268 ]]
[[0.00136685 0.9986331 ]]
[[0.00118055 0.9988194 ]]
[[0.00683303 0.993167  ]]
[[0.00190352 0.9980965 ]]
[[0.00196732 0.9980326 ]]
[[6.4426498e-04 9.9935573e-01]]
[[0.00147363 0.99852633]]
[[0.01780275 0.9821973 ]]
[[0.00219696 0.99780303]]
[[0.0050463 0.9949537]]
[[0.00107592 0.9989241 ]]
[[0.00228473 0.99771523]]
[[0.00796923 0.99203074]]
[[0.00164493 0.9983551 ]]
[[0.02269666 0.9773033 ]]
[[0.0018449  0.99815506]]
[[0.00381797 0.996182  ]]
[[0.00378568 0.99621433]]
[[0.00126343 0.99873656]]
[[0.00188966 0.9981103 ]]
[[0.08393243 0.91606754]]
[[0.00188796 0.9981121 ]]
[[7.712734e-04 9.992287e-01]]
[[0.00155479 0.9984452 ]]
[[0.00350052 0.9964994 ]]
[[0.0034133 0.9965867]]
[[0.00197981 0.9980202 ]]
[[0.04331226 0.9566877 ]]
[[0.00347869 0.99652135]]
[[0.2018176  0.79818237]]
[[8.5557369e-04 9.9914443e-01]]
[[0.00513554 0.9948645 ]]
[[0.00201519 0.99798477]]
[[0.042076   0.95792395]]
[[0.00364907 0.9963509 ]]
[[8.3545956e-04 9.9916458e

[[0.01822527 0.9817747 ]]
[[0.00220597 0.99779403]]
[[0.00234133 0.9976586 ]]
[[0.05281378 0.94718623]]
[[0.00459872 0.99540126]]
[[0.00378308 0.99621695]]
[[0.00157434 0.9984257 ]]
[[0.00314138 0.9968586 ]]
[[0.07807735 0.9219226 ]]
[[0.02761482 0.9723851 ]]
[[0.01797148 0.9820285 ]]
[[0.00102982 0.99897015]]
[[0.03516602 0.964834  ]]
[[0.00308497 0.996915  ]]
[[9.8584010e-04 9.9901414e-01]]
[[0.01573948 0.9842605 ]]
[[0.00142623 0.9985738 ]]
[[0.11778211 0.88221794]]
[[0.00175808 0.9982419 ]]
[[0.00871577 0.99128425]]
[[0.03225754 0.9677424 ]]
[[0.03606631 0.9639337 ]]
[[0.00775487 0.99224514]]
[[0.00102167 0.9989784 ]]
[[0.1814385  0.81856143]]
[[0.03785897 0.962141  ]]
[[0.01164896 0.98835105]]
[[0.00159798 0.99840206]]
[[0.00593907 0.99406093]]
[[0.02397374 0.97602624]]
[[0.07674322 0.9232568 ]]
[[0.14742348 0.85257655]]
[[0.01868085 0.98131907]]
[[0.02093778 0.9790622 ]]
[[0.04337081 0.9566292 ]]
[[0.15701497 0.84298503]]
[[0.00421843 0.99578154]]
[[0.02263488 0.9773652 ]]
[[0.00

[[0.02169138 0.9783086 ]]
[[0.07736262 0.9226374 ]]
[[0.00186579 0.9981342 ]]
[[0.00113899 0.9988611 ]]
[[0.1040735 0.8959265]]
[[0.07429867 0.9257013 ]]
[[0.01684194 0.983158  ]]
[[0.00454104 0.99545896]]
[[0.03442064 0.9655794 ]]
[[0.00537383 0.9946261 ]]
[[0.01821717 0.98178285]]
[[0.10120846 0.8987916 ]]
[[0.08537466 0.91462535]]
[[0.00221655 0.9977835 ]]
[[0.05788961 0.94211036]]
[[0.05114916 0.9488508 ]]
[[0.0035835  0.99641645]]
[[0.02318054 0.97681946]]
[[0.00244288 0.99755704]]
[[0.00360764 0.9963923 ]]
[[0.00179187 0.99820817]]
[[0.00450154 0.99549854]]
[[0.00305331 0.99694675]]
[[0.00206733 0.9979327 ]]
[[0.03318704 0.96681297]]
[[0.24927846 0.7507215 ]]
[[0.01317975 0.9868203 ]]
[[0.0040649 0.9959351]]
[[0.00845244 0.9915475 ]]
[[9.2580734e-04 9.9907422e-01]]
[[0.00424936 0.99575067]]
[[0.03555478 0.9644453 ]]
[[0.04653135 0.9534687 ]]
[[0.00189562 0.99810433]]
[[0.00113711 0.99886286]]
[[8.2861545e-04 9.9917138e-01]]
[[0.10968444 0.89031553]]
[[0.00193723 0.9980628 ]]
[[0.

[[0.00226929 0.9977307 ]]
[[0.00187567 0.9981243 ]]
[[0.01806019 0.98193985]]
[[0.00417903 0.995821  ]]
[[0.00749791 0.9925021 ]]
[[0.00804083 0.9919592 ]]
[[0.01121316 0.98878676]]
[[0.00374494 0.99625504]]
[[0.02643707 0.97356296]]
[[0.00361369 0.9963863 ]]
[[0.01492543 0.9850745 ]]
[[0.00467693 0.9953231 ]]
[[0.00121734 0.9987827 ]]
[[0.00144947 0.9985505 ]]
[[0.00364409 0.9963559 ]]
[[0.0535773 0.9464227]]
[[0.0110952 0.9889048]]
[[0.00169703 0.99830294]]
[[0.00272283 0.9972772 ]]
[[0.00120245 0.99879754]]
[[0.03162928 0.9683707 ]]
[[0.00329431 0.9967057 ]]
[[0.16333735 0.83666265]]
[[0.00593135 0.9940686 ]]
[[0.00466687 0.99533314]]
[[0.00329962 0.99670035]]
[[0.00118137 0.9988186 ]]
[[0.00428814 0.9957119 ]]
[[0.00183248 0.9981675 ]]
[[0.00645302 0.993547  ]]
[[0.03853685 0.9614631 ]]
[[0.10201263 0.89798737]]
[[0.05175965 0.94824034]]
[[0.02075255 0.9792475 ]]
[[0.12522465 0.8747754 ]]
[[0.00157331 0.9984267 ]]
[[0.00126617 0.9987338 ]]
[[0.00124969 0.9987503 ]]
[[0.03264635 0.9

[[0.00177406 0.998226  ]]
[[0.00895882 0.99104124]]
[[0.00274516 0.9972549 ]]
[[8.5556391e-04 9.9914443e-01]]
[[0.01023606 0.989764  ]]
[[0.0012643 0.9987357]]
[[9.0517872e-04 9.9909484e-01]]
[[0.00180604 0.9981939 ]]
[[0.00261326 0.99738675]]
[[0.00345673 0.9965432 ]]
[[0.0165062 0.9834938]]
[[0.00183686 0.99816316]]
[[0.00404386 0.9959561 ]]
[[7.901009e-04 9.992099e-01]]
[[0.07211278 0.9278872 ]]
[[0.00184201 0.99815804]]
[[0.04153888 0.9584611 ]]
[[0.00302627 0.99697375]]
[[0.0033476 0.9966524]]
[[0.00640416 0.9935959 ]]
[[0.08400333 0.9159967 ]]
[[0.00183146 0.99816847]]
[[0.00230831 0.99769175]]
[[0.0453897  0.95461035]]
[[0.00174627 0.99825376]]
[[0.00306215 0.9969379 ]]
[[7.7735080e-04 9.9922264e-01]]
[[0.13491568 0.8650843 ]]
[[0.00139709 0.9986029 ]]
[[0.00994831 0.9900517 ]]
[[0.00666216 0.99333787]]
[[0.00148714 0.9985128 ]]
[[0.00879699 0.99120307]]
[[0.0011319 0.9988681]]
[[0.01874422 0.9812557 ]]
[[0.00408675 0.9959132 ]]
[[0.00884974 0.99115026]]
[[0.00163997 0.99836   ]

[[0.08373265 0.91626734]]
[[0.00618422 0.9938158 ]]
[[0.00582967 0.9941703 ]]
[[8.310799e-04 9.991690e-01]]
[[0.00921447 0.9907856 ]]
[[0.0049341 0.9950659]]
[[0.08310643 0.9168936 ]]
[[0.19325061 0.80674934]]
[[0.06652253 0.9334774 ]]
[[9.738676e-04 9.990262e-01]]
[[0.0041567  0.99584335]]
[[0.00796765 0.9920324 ]]
[[0.00273564 0.9972644 ]]
[[0.00381369 0.9961863 ]]
[[0.01998354 0.98001647]]
[[0.001163   0.99883705]]
[[0.02906451 0.9709355 ]]
[[0.01154956 0.9884504 ]]
[[0.00961406 0.990386  ]]
[[9.9666615e-04 9.9900335e-01]]
[[0.03290782 0.9670922 ]]
[[0.00156383 0.99843615]]
[[0.03008646 0.9699136 ]]
[[0.00275238 0.99724764]]
[[0.02030642 0.9796936 ]]
[[0.0064531 0.9935469]]
[[0.01273847 0.98726153]]
[[0.00424202 0.995758  ]]
[[0.00145819 0.99854183]]
[[0.00791058 0.9920894 ]]
[[0.00212111 0.9978789 ]]
[[0.03655191 0.9634481 ]]
[[0.00135315 0.9986469 ]]
[[0.01276124 0.9872387 ]]
[[0.00271269 0.9972873 ]]
[[0.5068067  0.49319333]]
[[0.00212861 0.9978714 ]]
[[0.00199417 0.9980058 ]]
[[

[[0.08654335 0.9134567 ]]
[[0.00344904 0.9965509 ]]
[[0.00436716 0.9956328 ]]
[[0.00113845 0.99886155]]
[[0.00792785 0.99207217]]
[[0.08896809 0.9110319 ]]
[[0.00260593 0.9973941 ]]
[[0.00229463 0.9977054 ]]
[[0.00168851 0.9983115 ]]
[[8.0069032e-04 9.9919933e-01]]
[[0.00703754 0.9929624 ]]
[[0.01074567 0.98925436]]
[[0.0031535 0.9968465]]
[[0.00220869 0.9977913 ]]
[[0.00757662 0.9924233 ]]
[[0.00317191 0.996828  ]]
[[0.00166425 0.9983358 ]]
[[0.00179647 0.9982035 ]]
[[0.07166984 0.9283302 ]]
[[0.00533314 0.99466693]]
[[0.01250965 0.98749036]]
[[0.03705037 0.9629497 ]]
[[0.00166313 0.9983368 ]]
[[0.00566938 0.99433064]]
[[0.00270539 0.9972946 ]]
[[0.00273865 0.9972613 ]]
[[0.00305406 0.9969459 ]]
[[0.00734825 0.99265176]]
[[0.00349961 0.9965004 ]]
[[0.00553871 0.9944613 ]]
[[0.03443346 0.9655665 ]]
[[0.00132898 0.99867105]]
[[0.00158433 0.9984157 ]]
[[0.0087784  0.99122155]]
[[0.00348539 0.9965146 ]]
[[0.00159832 0.9984017 ]]
[[0.06516443 0.9348356 ]]
[[0.13953659 0.86046344]]
[[0.0162

[[0.00244244 0.9975575 ]]
[[0.00807005 0.99193   ]]
[[0.01839665 0.9816034 ]]
[[0.00140677 0.9985933 ]]
[[0.00161668 0.9983833 ]]
[[0.04847321 0.9515268 ]]
[[0.01280656 0.9871934 ]]
[[0.00365464 0.99634534]]
[[9.4337651e-04 9.9905664e-01]]
[[0.10361695 0.89638305]]
[[0.00175465 0.99824536]]
[[0.00821705 0.9917829 ]]
[[0.00416351 0.9958365 ]]
[[0.21272053 0.7872795 ]]
[[0.00573694 0.994263  ]]
[[0.01855379 0.9814462 ]]
[[0.00456662 0.9954334 ]]
[[0.01037547 0.98962456]]
[[0.05124629 0.9487537 ]]
[[0.2569193 0.7430807]]
[[0.00500016 0.9949999 ]]
[[0.07906099 0.920939  ]]
[[0.02624233 0.9737577 ]]
[[0.00304013 0.9969599 ]]
[[0.01834102 0.981659  ]]
[[0.00200639 0.9979936 ]]
[[0.00325566 0.9967443 ]]
[[0.08147203 0.91852796]]
[[0.00236902 0.99763095]]
[[9.798715e-04 9.990201e-01]]
[[0.00494745 0.9950525 ]]
[[0.00398989 0.99601007]]
[[0.01517401 0.98482597]]
[[0.04956664 0.95043343]]
[[0.00450154 0.99549854]]
[[0.01054739 0.9894526 ]]
[[0.00339924 0.9966008 ]]
[[0.00335581 0.99664426]]
[[0.

[[0.00427676 0.99572325]]
[[0.00842122 0.9915788 ]]
[[0.03747841 0.9625216 ]]
[[0.00123395 0.99876606]]
[[0.01582047 0.98417956]]
[[0.00512302 0.99487704]]
[[0.03337186 0.9666282 ]]
[[0.02856989 0.9714301 ]]
[[0.00116516 0.9988349 ]]
[[0.04755217 0.95244783]]
[[0.00433095 0.995669  ]]
[[0.00275725 0.9972428 ]]
[[0.01021475 0.98978525]]
[[0.02190005 0.9781    ]]
[[0.0384618 0.9615382]]
[[8.2021265e-04 9.9917978e-01]]
[[0.00128252 0.99871755]]
[[0.00450154 0.99549854]]
[[0.02023941 0.9797606 ]]
[[0.02269418 0.9773058 ]]
[[0.00242154 0.99757844]]
[[0.00343056 0.9965694 ]]
[[0.00263204 0.99736804]]
[[0.0263006 0.9736994]]
[[0.00768802 0.992312  ]]
[[0.00515423 0.99484575]]
[[0.00114178 0.9988582 ]]
[[0.00653453 0.9934655 ]]
[[0.00374501 0.9962549 ]]
[[0.01259821 0.9874018 ]]
[[0.04965044 0.9503495 ]]
[[0.01439717 0.98560286]]
[[0.00240458 0.99759537]]
[[0.00152972 0.99847025]]
[[0.05663025 0.94336975]]
[[0.00550854 0.99449146]]
[[0.00231488 0.9976851 ]]
[[0.00959171 0.9904083 ]]
[[0.002566

[[0.09668881 0.90331125]]
[[0.00102942 0.9989706 ]]
[[0.00274729 0.99725276]]
[[0.00504234 0.9949576 ]]
[[0.02127058 0.9787295 ]]
[[0.02483626 0.9751637 ]]
[[0.00505394 0.99494606]]
[[0.00156313 0.99843687]]
[[0.01932406 0.98067594]]
[[0.05947923 0.94052076]]
[[0.09760341 0.90239656]]
[[0.03110094 0.9688991 ]]
[[0.01133951 0.98866045]]
[[0.00429538 0.9957046 ]]
[[0.06642249 0.9335775 ]]
[[0.08596162 0.91403836]]
[[0.00569523 0.9943047 ]]
[[0.00705522 0.9929448 ]]
[[0.13554537 0.8644546 ]]
[[0.00450154 0.99549854]]
[[0.00766317 0.9923368 ]]
[[0.0016897 0.9983103]]
[[0.002725   0.99727505]]
[[0.03070394 0.96929604]]
[[0.00194104 0.998059  ]]
[[0.00136886 0.99863106]]
[[0.0105785 0.9894215]]
[[0.00450154 0.99549854]]
[[0.01387664 0.9861233 ]]
[[0.01653942 0.9834606 ]]
[[0.01811756 0.9818825 ]]
[[0.00183161 0.99816835]]
[[0.00971609 0.9902839 ]]
[[0.08535466 0.9146453 ]]
[[0.0037492 0.9962508]]
[[0.01351479 0.98648524]]
[[0.00497178 0.9950282 ]]
[[0.00370935 0.9962907 ]]
[[0.00164978 0.998

[[0.00303628 0.9969637 ]]
[[0.01571708 0.9842829 ]]
[[0.00186073 0.99813926]]
[[0.07771439 0.9222856 ]]
[[0.05218023 0.94781977]]
[[0.06982254 0.93017745]]
[[0.00331558 0.9966844 ]]
[[0.0015588  0.99844116]]
[[0.00206023 0.99793977]]
[[0.00120433 0.9987956 ]]
[[0.00841823 0.99158174]]
[[0.02352799 0.97647196]]
[[0.00168592 0.99831414]]
[[0.00246395 0.99753606]]
[[0.00270761 0.99729234]]
[[0.0033683 0.9966317]]
[[0.00197057 0.9980294 ]]
[[0.01714686 0.9828531 ]]
[[0.00776748 0.99223256]]
[[0.00523479 0.99476516]]
[[0.00422684 0.99577314]]
[[0.00921075 0.99078923]]
[[0.00257907 0.9974209 ]]
[[0.00141585 0.99858415]]
[[0.04659409 0.9534059 ]]
[[0.00222248 0.9977775 ]]
[[0.00490484 0.99509513]]
[[0.00178483 0.9982152 ]]
[[0.00168196 0.9983181 ]]
[[0.00139767 0.99860233]]
[[0.00521603 0.99478394]]
[[0.00384675 0.9961532 ]]
[[0.00178583 0.99821424]]
[[0.00466613 0.99533385]]
[[0.02422242 0.9757776 ]]
[[0.01875927 0.9812407 ]]
[[0.00117582 0.9988242 ]]
[[0.03370172 0.9662982 ]]
[[0.00302406 0

[[0.00829738 0.9917026 ]]
[[0.00269593 0.9973041 ]]
[[0.02468764 0.97531235]]
[[0.00177287 0.9982272 ]]
[[0.06982363 0.9301764 ]]
[[0.00281778 0.99718225]]
[[0.00135847 0.99864155]]
[[0.02003326 0.9799667 ]]
[[0.00144036 0.99855965]]
[[0.00255614 0.9974439 ]]
[[0.00568088 0.99431914]]
[[0.02210118 0.97789884]]
[[0.00484438 0.9951557 ]]
[[0.00812631 0.9918737 ]]
[[0.00153998 0.99846005]]
[[0.0412722  0.95872784]]
[[0.0385652 0.9614348]]
[[0.17760627 0.82239366]]
[[0.95893896 0.0410611 ]]
[[0.01170571 0.98829424]]
[[0.00334598 0.99665403]]
[[0.00144356 0.99855644]]
[[0.03189997 0.9681    ]]
[[0.00504968 0.9949503 ]]
[[0.00201956 0.9979804 ]]
[[9.4299635e-04 9.9905699e-01]]
[[0.00145483 0.99854517]]
[[0.00123342 0.99876666]]
[[0.0132287 0.9867713]]
[[0.00131216 0.9986878 ]]
[[0.01679815 0.9832018 ]]
[[0.01806967 0.9819303 ]]
[[0.16103972 0.8389603 ]]
[[0.0010986  0.99890137]]
[[0.03330463 0.9666953 ]]
[[0.00154957 0.9984504 ]]
[[0.00378682 0.9962132 ]]
[[0.01122968 0.98877037]]
[[0.010354

[[0.00582509 0.9941749 ]]
[[0.00213282 0.9978671 ]]
[[0.00844184 0.9915582 ]]
[[0.02955213 0.9704479 ]]
[[0.00100408 0.99899596]]
[[0.00790126 0.9920988 ]]
[[0.02138992 0.97861004]]
[[0.01425457 0.98574543]]
[[0.00129787 0.99870217]]
[[0.00273161 0.99726844]]
[[0.00190336 0.99809664]]
[[0.00419609 0.9958039 ]]
[[8.4668869e-04 9.9915326e-01]]
[[0.00398307 0.9960169 ]]
[[0.00247331 0.9975267 ]]
[[0.00107357 0.99892646]]
[[0.0022286 0.9977714]]
[[0.00394607 0.99605393]]
[[0.00173307 0.99826694]]
[[0.00117251 0.9988275 ]]
[[0.00146424 0.99853575]]
[[9.4209478e-04 9.9905795e-01]]
[[0.00376253 0.9962374 ]]
[[0.00193173 0.9980683 ]]
[[0.00357651 0.9964234 ]]
[[0.01847913 0.98152083]]
[[0.00141413 0.99858594]]
[[0.00450154 0.99549854]]
[[0.00173173 0.99826825]]
[[0.0747655 0.9252345]]
[[0.00124094 0.99875903]]
[[0.00149642 0.99850357]]
[[0.00628177 0.99371827]]
[[0.00104703 0.998953  ]]
[[0.11154117 0.88845885]]
[[0.01314195 0.986858  ]]
[[0.00170493 0.9982951 ]]
[[0.0036879 0.9963121]]
[[0.04

[[0.00349179 0.9965082 ]]
[[0.0090734 0.9909266]]
[[0.00360078 0.99639916]]
[[0.00151217 0.99848783]]
[[0.16487467 0.8351254 ]]
[[0.00182956 0.9981704 ]]
[[0.07547025 0.9245298 ]]
[[0.00233597 0.9976641 ]]
[[0.00229096 0.99770904]]
[[0.04373074 0.95626926]]
[[0.00333227 0.9966677 ]]
[[0.00254936 0.99745065]]
[[9.3950244e-04 9.9906045e-01]]
[[0.00110825 0.9988918 ]]
[[0.00225912 0.99774086]]
[[0.00202485 0.9979752 ]]
[[0.0116849 0.9883151]]
[[0.00479381 0.9952062 ]]
[[0.04097285 0.9590272 ]]
[[0.00292306 0.997077  ]]
[[0.00184705 0.9981529 ]]
[[0.00888974 0.9911103 ]]
[[0.05151345 0.94848657]]
[[0.001848   0.99815196]]
[[0.01965793 0.9803421 ]]
[[0.01628919 0.9837108 ]]
[[0.00365112 0.99634886]]
[[0.00676055 0.9932394 ]]
[[0.00182501 0.998175  ]]
[[0.00252188 0.99747807]]
[[0.00138478 0.99861526]]
[[0.00652697 0.993473  ]]
[[0.00318594 0.9968141 ]]
[[0.00330242 0.99669766]]
[[0.00733285 0.99266714]]
[[0.00133068 0.9986694 ]]
[[0.01266109 0.9873389 ]]
[[0.00383678 0.99616325]]
[[0.002062

[[0.0425856 0.9574143]]
[[0.00106462 0.9989354 ]]
[[0.06863684 0.9313631 ]]
[[0.00138269 0.9986173 ]]
[[9.925314e-04 9.990075e-01]]
[[0.00693587 0.9930641 ]]
[[0.005995 0.994005]]
[[0.00138429 0.99861574]]
[[0.5701368  0.42986327]]
[[0.0013101  0.99868995]]
[[0.00213617 0.9978638 ]]
[[9.257005e-04 9.990742e-01]]
[[0.02970647 0.9702936 ]]
[[0.03220401 0.967796  ]]
[[7.3551433e-04 9.9926454e-01]]
[[0.05370583 0.9462941 ]]
[[0.03922932 0.96077067]]
[[0.00197687 0.99802315]]
[[0.0084043 0.9915957]]
[[0.00189115 0.99810886]]
[[0.00566701 0.994333  ]]
[[0.00127606 0.9987239 ]]
[[0.03101492 0.968985  ]]
[[0.00178577 0.99821424]]
[[0.00337455 0.9966254 ]]
[[0.00175736 0.9982426 ]]
[[0.01250965 0.98749036]]
[[7.1638357e-04 9.9928361e-01]]
[[0.00235457 0.99764544]]
[[0.00867616 0.9913238 ]]
[[0.00184554 0.99815446]]
[[0.00242322 0.9975768 ]]
[[0.00273606 0.9972639 ]]
[[0.0013464  0.99865353]]
[[0.00329202 0.9967079 ]]
[[0.2265743  0.77342576]]
[[0.00440841 0.9955916 ]]
[[0.03277839 0.9672217 ]]


[[0.00173869 0.9982613 ]]
[[0.00443231 0.99556774]]
[[0.00612264 0.99387735]]
[[0.0018606 0.9981394]]
[[0.02508116 0.9749188 ]]
[[0.00374781 0.99625224]]
[[0.00184569 0.99815434]]
[[0.00168538 0.9983146 ]]
[[0.01869675 0.9813033 ]]
[[0.00280781 0.9971922 ]]
[[0.00213949 0.9978605 ]]
[[0.00131399 0.998686  ]]
[[0.00216788 0.9978321 ]]
[[0.01885605 0.98114395]]
[[9.6989237e-04 9.9903011e-01]]
[[0.02709114 0.97290885]]
[[0.0055408  0.99445915]]
[[0.00487326 0.9951267 ]]
[[0.00737758 0.9926224 ]]
[[0.01670462 0.9832954 ]]
[[0.00417243 0.9958276 ]]
[[0.00379067 0.9962094 ]]
[[0.00453389 0.9954661 ]]
[[0.0013913  0.99860877]]
[[0.00789702 0.99210304]]
[[0.01152795 0.9884721 ]]
[[0.00277978 0.9972203 ]]
[[0.02418975 0.97581017]]
[[0.00126162 0.99873835]]
[[0.01639354 0.98360646]]
[[0.00729071 0.9927093 ]]
[[0.00665606 0.99334395]]
[[0.00967252 0.99032754]]
[[0.00437671 0.9956233 ]]
[[0.00412244 0.9958775 ]]
[[0.04678679 0.9532132 ]]
[[0.02579786 0.9742021 ]]
[[0.00450154 0.99549854]]
[[0.0481

[[0.00137678 0.99862325]]
[[0.10543077 0.8945692 ]]
[[0.00126518 0.9987348 ]]
[[0.00159062 0.99840945]]
[[0.00576346 0.9942365 ]]
[[0.00116779 0.99883217]]
[[0.00203269 0.9979673 ]]
[[0.00421395 0.995786  ]]
[[0.10326394 0.896736  ]]
[[0.00601571 0.9939843 ]]
[[0.00337663 0.9966234 ]]
[[0.0049165 0.9950836]]
[[0.001042 0.998958]]
[[0.00255541 0.9974446 ]]
[[0.00293669 0.99706334]]
[[0.01337363 0.9866263 ]]
[[8.520403e-04 9.991479e-01]]
[[0.00237788 0.9976221 ]]
[[0.0013894 0.9986106]]
[[0.00296543 0.99703455]]
[[0.00266318 0.9973368 ]]
[[0.00666794 0.9933321 ]]
[[0.03798475 0.96201533]]
[[0.02017292 0.97982705]]
[[0.00427862 0.99572134]]
[[0.00196318 0.9980368 ]]
[[0.00104544 0.99895453]]
[[0.01026705 0.9897329 ]]
[[0.08225621 0.9177438 ]]
[[0.00127619 0.9987238 ]]
[[0.00489427 0.99510574]]
[[0.12720369 0.87279636]]
[[0.0034762 0.9965238]]
[[0.00296894 0.9970311 ]]
[[0.04110349 0.9588965 ]]
[[0.00450154 0.99549854]]
[[0.00153864 0.99846137]]
[[0.00550431 0.9944957 ]]
[[0.00165036 0.998

[[0.00879457 0.9912054 ]]
[[0.00216157 0.99783844]]
[[0.00182236 0.99817765]]
[[0.01395381 0.98604625]]
[[0.03242613 0.9675739 ]]
[[0.08276407 0.917236  ]]
[[0.00255352 0.99744654]]
[[0.00450154 0.99549854]]
[[0.00309947 0.99690056]]
[[0.00253139 0.9974686 ]]
[[0.00573746 0.9942625 ]]
[[0.00110519 0.9988949 ]]
[[0.00583609 0.99416393]]
[[0.02264522 0.9773548 ]]
[[0.00193087 0.9980691 ]]
[[0.00400159 0.9959984 ]]
[[0.00642479 0.99357516]]
[[0.00114595 0.99885404]]
[[0.14706428 0.8529358 ]]
[[0.00154817 0.9984518 ]]
[[0.00241415 0.9975859 ]]
[[0.00363409 0.9963659 ]]
[[0.00144864 0.9985513 ]]
[[0.00257957 0.99742043]]
[[0.1550293 0.8449707]]
[[0.00850496 0.991495  ]]
[[0.01158178 0.9884183 ]]
[[0.00143924 0.9985607 ]]
[[0.14588664 0.8541134 ]]
[[0.01806019 0.98193985]]
[[0.00486928 0.9951308 ]]
[[0.00246193 0.9975381 ]]
[[0.00298234 0.9970176 ]]
[[0.00164897 0.9983511 ]]
[[8.851750e-04 9.991148e-01]]
[[0.00307695 0.996923  ]]
[[0.06404553 0.93595445]]
[[0.00222312 0.9977769 ]]
[[0.011216

[[0.03115976 0.9688402 ]]
[[0.00935583 0.9906441 ]]
[[0.00830553 0.9916945 ]]
[[0.04758522 0.95241475]]
[[0.00226705 0.9977329 ]]
[[0.00205706 0.997943  ]]
[[0.08379266 0.9162073 ]]
[[0.00540038 0.9945996 ]]
[[0.00282362 0.9971764 ]]
[[0.00375649 0.9962435 ]]
[[0.01431334 0.9856866 ]]
[[0.00569896 0.9943011 ]]
[[0.0071747  0.99282527]]
[[0.00127927 0.9987207 ]]
[[0.00172574 0.9982742 ]]
[[0.785195   0.21480502]]
[[0.09077712 0.9092229 ]]
[[0.00268471 0.9973152 ]]
[[0.00594432 0.9940556 ]]
[[0.22187048 0.7781295 ]]
[[0.00107042 0.99892956]]
[[0.050374 0.949626]]
[[0.00288243 0.99711764]]
[[0.00859244 0.9914076 ]]
[[0.01208865 0.98791134]]
[[0.0039442  0.99605584]]
[[0.00235728 0.9976427 ]]
[[0.06592882 0.93407124]]
[[0.08846509 0.9115349 ]]
[[0.00446042 0.9955396 ]]
[[0.00151547 0.99848455]]
[[0.16367441 0.8363256 ]]
[[0.00279396 0.99720603]]
[[0.01724792 0.98275214]]
[[0.01426251 0.98573744]]
[[0.01381459 0.9861854 ]]
[[0.00363304 0.996367  ]]
[[0.03576386 0.9642362 ]]
[[8.735794e-04 9

[[0.13782358 0.86217636]]
[[0.00133141 0.99866855]]
[[0.00591214 0.9940878 ]]
[[0.00332155 0.9966785 ]]
[[0.00184191 0.99815804]]
[[0.03663004 0.96337   ]]
[[0.00490991 0.99509   ]]
[[0.00715749 0.99284256]]
[[0.00318621 0.99681383]]
[[0.00131257 0.99868745]]
[[0.00273679 0.9972632 ]]
[[0.11722576 0.88277423]]
[[0.0015217  0.99847835]]
[[0.00254305 0.99745697]]
[[0.00368205 0.996318  ]]
[[0.3020503  0.69794965]]
[[0.00568939 0.9943106 ]]
[[0.00161778 0.9983822 ]]
[[0.00132163 0.9986784 ]]
[[8.636754e-04 9.991364e-01]]
[[0.04511702 0.954883  ]]
[[0.00198756 0.9980124 ]]
[[0.00965966 0.9903404 ]]
[[0.00270742 0.9972926 ]]
[[0.00415536 0.99584466]]
[[0.00450154 0.99549854]]
[[0.00200207 0.99799794]]
[[0.00235637 0.99764365]]
[[0.00345798 0.99654204]]
[[0.00425503 0.995745  ]]
[[8.6521648e-04 9.9913484e-01]]
[[0.0053859  0.99461406]]
[[0.0027542 0.9972458]]
[[0.02046174 0.97953826]]
[[0.01446098 0.9855391 ]]
[[0.00523421 0.99476576]]
[[0.0048824  0.99511766]]
[[0.00466182 0.9953382 ]]
[[0.

[[0.00272131 0.99727875]]
[[0.00194842 0.99805164]]
[[0.01428302 0.98571694]]
[[0.00163751 0.9983625 ]]
[[0.06576684 0.9342331 ]]
[[0.11161134 0.88838863]]
[[0.00107142 0.9989286 ]]
[[0.02485227 0.9751477 ]]
[[0.16210341 0.8378965 ]]
[[0.00394308 0.9960569 ]]
[[0.11680417 0.8831958 ]]
[[0.00592927 0.9940707 ]]
[[0.00130942 0.99869055]]
[[0.02731111 0.97268885]]
[[0.00241027 0.9975897 ]]
[[0.00450154 0.99549854]]
[[0.00633611 0.9936639 ]]
[[0.00300725 0.9969927 ]]
[[0.08181257 0.91818744]]
[[0.19178791 0.8082121 ]]
[[0.00768797 0.992312  ]]
[[0.00277001 0.99723   ]]
[[0.00199817 0.9980019 ]]
[[0.00336137 0.99663866]]
[[0.00700983 0.99299014]]
[[0.23682958 0.7631704 ]]
[[0.00692273 0.9930773 ]]
[[0.00430816 0.99569184]]
[[0.01164631 0.9883536 ]]
[[0.38213903 0.617861  ]]
[[8.8681484e-04 9.9911314e-01]]
[[0.0132061  0.98679394]]
[[0.0010547 0.9989453]]
[[0.00268436 0.9973156 ]]
[[0.00441519 0.9955848 ]]
[[0.04514146 0.95485854]]
[[0.00516848 0.9948315 ]]
[[0.03911525 0.9608847 ]]
[[0.0020

[[0.01375819 0.9862418 ]]
[[0.39812174 0.60187835]]
[[0.00139597 0.998604  ]]
[[0.00302753 0.99697244]]
[[0.00130529 0.9986947 ]]
[[0.00113772 0.99886227]]
[[0.00546243 0.99453753]]
[[9.744653e-04 9.990256e-01]]
[[0.00206473 0.9979353 ]]
[[0.00198326 0.9980167 ]]
[[0.00181354 0.9981864 ]]
[[0.00517441 0.9948256 ]]
[[0.02002785 0.9799722 ]]
[[0.00390195 0.99609804]]
[[0.00429968 0.99570036]]
[[0.00173518 0.99826485]]
[[0.16524777 0.83475226]]
[[0.02436928 0.97563076]]
[[0.00282571 0.99717426]]
[[0.00561108 0.9943889 ]]
[[0.00260749 0.99739254]]
[[0.0045579  0.99544203]]
[[0.00554478 0.9944553 ]]
[[0.01225244 0.98774755]]
[[0.00445283 0.9955472 ]]
[[0.00202642 0.9979736 ]]
[[0.01097204 0.989028  ]]
[[0.00812371 0.99187624]]
[[0.01575969 0.9842403 ]]
[[0.00534595 0.99465406]]
[[0.04942811 0.9505719 ]]
[[9.636842e-04 9.990363e-01]]
[[0.00463729 0.99536264]]
[[0.00412827 0.9958717 ]]
[[7.800533e-04 9.992199e-01]]
[[0.01540697 0.9845931 ]]
[[0.01385954 0.9861405 ]]
[[0.00228111 0.9977189 ]]


[[0.00104228 0.99895775]]
[[0.00231151 0.99768853]]
[[0.00309292 0.99690706]]
[[0.01248695 0.987513  ]]
[[0.00545633 0.9945437 ]]
[[0.0064661  0.99353385]]
[[0.00108733 0.9989127 ]]
[[0.00186447 0.99813545]]
[[0.00188433 0.99811566]]
[[0.00505583 0.99494416]]
[[0.01552285 0.98447716]]
[[0.03299894 0.967001  ]]
[[0.00421367 0.99578637]]
[[8.1054063e-04 9.9918944e-01]]
[[0.00198049 0.99801946]]
[[0.00722012 0.9927799 ]]
[[0.00168808 0.9983119 ]]
[[0.0144758 0.9855241]]
[[0.00146001 0.99854004]]
[[0.00143833 0.9985617 ]]
[[0.00253194 0.9974681 ]]
[[0.33358884 0.66641116]]
[[0.03655776 0.96344227]]
[[0.00253862 0.9974613 ]]
[[0.06915558 0.9308444 ]]
[[0.00695204 0.993048  ]]
[[0.00793434 0.9920657 ]]
[[0.0119658 0.9880342]]
[[0.00209818 0.9979018 ]]
[[0.03843826 0.96156174]]
[[0.001611 0.998389]]
[[0.03479351 0.9652065 ]]
[[0.00132929 0.9986707 ]]
[[0.00995769 0.9900423 ]]
[[0.01003135 0.9899686 ]]
[[0.16919398 0.8308061 ]]
[[0.00928638 0.9907136 ]]
[[0.00285858 0.9971414 ]]
[[0.00394722 0

[[0.00286446 0.9971355 ]]
[[0.01297233 0.98702765]]
[[0.01106806 0.9889319 ]]
[[0.00248193 0.99751806]]
[[0.00506889 0.99493104]]
[[0.00212023 0.99787974]]
[[0.00222911 0.9977709 ]]
[[0.00136522 0.99863476]]
[[0.02231127 0.97768867]]
[[0.00297202 0.99702805]]
[[0.00154483 0.99845517]]
[[0.20883559 0.7911644 ]]
[[0.00110187 0.99889815]]
[[0.00728874 0.9927113 ]]
[[0.00202497 0.99797505]]
[[0.00883385 0.9911662 ]]
[[0.00396049 0.9960395 ]]
[[0.00237474 0.9976253 ]]
[[0.27100366 0.7289964 ]]
[[0.00107102 0.99892896]]
[[0.01867926 0.9813207 ]]
[[0.00289419 0.9971058 ]]
[[0.00276783 0.99723214]]
[[0.00791824 0.99208176]]
[[0.0986942 0.9013058]]
[[0.09018953 0.9098105 ]]
[[0.00211325 0.9978867 ]]
[[0.00283048 0.99716955]]
[[0.00193859 0.99806136]]
[[0.00107002 0.9989299 ]]
[[0.0020999 0.9979001]]
[[0.03445309 0.9655469 ]]
[[0.00202121 0.99797887]]
[[0.00499733 0.9950027 ]]
[[0.00198049 0.99801946]]
[[0.00524241 0.99475765]]
[[0.06301159 0.9369884 ]]
[[0.00789897 0.992101  ]]
[[0.00250096 0.9

[[0.00227368 0.9977264 ]]
[[0.0491317 0.9508683]]
[[0.00362373 0.9963762 ]]
[[0.0056237 0.9943763]]
[[0.00163497 0.998365  ]]
[[0.00647836 0.99352163]]
[[0.00205465 0.99794537]]
[[0.0195924  0.98040766]]
[[0.00603534 0.9939646 ]]
[[0.00118924 0.99881077]]
[[0.00760232 0.9923977 ]]
[[0.03209363 0.96790636]]
[[0.00145379 0.99854624]]
[[0.00961426 0.9903858 ]]
[[0.00373684 0.9962632 ]]
[[0.00428099 0.995719  ]]
[[0.02020923 0.97979075]]
[[0.00113874 0.9988613 ]]
[[0.07378983 0.9262102 ]]
[[0.00275569 0.99724436]]
[[0.01004949 0.98995054]]
[[0.00111381 0.99888617]]
[[0.00174005 0.99825996]]
[[0.24707565 0.7529243 ]]
[[0.00265691 0.9973431 ]]
[[0.00676469 0.9932353 ]]
[[0.06556536 0.9344347 ]]
[[7.1028067e-04 9.9928963e-01]]
[[0.02209386 0.97790617]]
[[0.1207967 0.8792033]]
[[0.00508391 0.9949161 ]]
[[0.00438584 0.9956142 ]]
[[0.00123752 0.9987625 ]]
[[0.0025761 0.9974239]]
[[0.10372321 0.89627683]]
[[0.07825583 0.9217441 ]]
[[0.00116311 0.99883693]]
[[0.00230802 0.997692  ]]
[[0.0068248 0.

[[0.00138758 0.9986124 ]]
[[0.01046685 0.9895331 ]]
[[9.645632e-04 9.990355e-01]]
[[0.1622644  0.83773565]]
[[0.00103548 0.99896455]]
[[0.063347 0.936653]]
[[0.00220234 0.9977977 ]]
[[0.00213082 0.99786913]]
[[0.00364092 0.99635905]]
[[0.00512557 0.9948744 ]]
[[0.02583143 0.97416854]]
[[0.00451493 0.99548507]]
[[0.01824727 0.98175275]]
[[0.03235868 0.9676413 ]]
[[0.02352529 0.9764747 ]]
[[0.03443179 0.9655682 ]]
[[0.00165323 0.9983468 ]]
[[0.09440308 0.905597  ]]
[[0.00379905 0.996201  ]]
[[0.00193252 0.99806744]]
[[0.0033609  0.99663913]]
[[0.01214552 0.9878544 ]]
[[0.00586222 0.99413776]]
[[0.01305865 0.9869414 ]]
[[0.11987785 0.8801222 ]]
[[0.00413856 0.9958615 ]]
[[0.00139295 0.9986071 ]]
[[0.0032315 0.9967685]]
[[0.00257265 0.9974273 ]]
[[0.00129156 0.9987085 ]]
[[0.00236612 0.9976338 ]]
[[0.00145287 0.99854714]]
[[0.00852244 0.99147755]]
[[0.00226009 0.9977399 ]]
[[0.00366295 0.99633706]]
[[0.00102257 0.9989774 ]]
[[0.17646879 0.82353115]]
[[0.0017623 0.9982377]]
[[9.041766e-04 9

[[0.003528 0.996472]]
[[0.0106625  0.98933756]]
[[0.01158956 0.9884105 ]]
[[0.01154564 0.9884544 ]]
[[0.02238625 0.9776137 ]]
[[0.00928761 0.99071246]]
[[0.00167784 0.9983222 ]]
[[0.00195539 0.9980446 ]]
[[0.00780907 0.9921909 ]]
[[0.00115067 0.9988493 ]]
[[0.0929402 0.9070598]]
[[0.20401415 0.7959858 ]]
[[0.00241249 0.99758756]]
[[0.00457897 0.995421  ]]
[[0.11290759 0.88709235]]
[[0.0092751  0.99072486]]
[[0.0120611 0.9879389]]
[[0.05901055 0.9409894 ]]
[[0.02595719 0.97404283]]
[[0.00515465 0.9948454 ]]
[[0.01823633 0.98176366]]
[[0.0043375 0.9956625]]
[[0.01599295 0.98400706]]
[[0.0015377 0.9984623]]
[[0.05032726 0.9496727 ]]
[[0.00151371 0.9984863 ]]
[[0.08740082 0.9125992 ]]
[[0.00359937 0.9964006 ]]
[[0.02839016 0.97160983]]
[[0.02562573 0.97437423]]
[[0.15866062 0.8413394 ]]
[[0.00407826 0.99592173]]
[[0.00225504 0.99774504]]
[[0.0054141 0.9945859]]
[[0.01666809 0.9833319 ]]
[[0.00379294 0.996207  ]]
[[0.00112066 0.9988794 ]]
[[0.00700964 0.9929904 ]]
[[0.01032871 0.9896713 ]]


[[0.00292042 0.9970796 ]]
[[0.00365574 0.99634427]]
[[0.00112829 0.99887174]]
[[0.00349252 0.99650747]]
[[0.002821   0.99717903]]
[[0.00383524 0.9961648 ]]
[[0.00217224 0.9978277 ]]
[[0.0012721  0.99872786]]
[[0.03774184 0.9622582 ]]
[[0.00270511 0.99729484]]
[[0.01889475 0.98110527]]
[[0.05066834 0.9493317 ]]
[[9.0071524e-04 9.9909925e-01]]
[[0.09515618 0.9048438 ]]
[[0.02127058 0.9787295 ]]
[[0.0049719 0.9950281]]
[[0.03691205 0.963088  ]]
[[0.00188796 0.9981121 ]]
[[0.00184172 0.9981583 ]]
[[0.02788249 0.9721175 ]]
[[0.34693375 0.6530663 ]]
[[0.01752348 0.9824766 ]]
[[0.01936281 0.9806372 ]]
[[0.00637775 0.99362224]]
[[0.00318445 0.9968156 ]]
[[0.00727264 0.9927274 ]]
[[0.0773844 0.9226156]]
[[0.00170838 0.9982917 ]]
[[0.00123014 0.9987698 ]]
[[0.00237628 0.99762374]]
[[0.00373169 0.99626833]]
[[0.00494542 0.9950546 ]]
[[0.00392923 0.99607074]]
[[0.00217666 0.99782336]]
[[0.00259013 0.9974099 ]]
[[0.00265209 0.99734783]]
[[0.00150878 0.99849117]]
[[0.00234776 0.99765223]]
[[0.112467

[[0.03108596 0.9689141 ]]
[[9.867835e-04 9.990132e-01]]
[[0.00125943 0.9987406 ]]
[[0.02849652 0.9715035 ]]
[[0.00962147 0.9903785 ]]
[[0.00568022 0.9943198 ]]
[[0.00450154 0.99549854]]
[[0.0081142 0.9918858]]
[[0.00888499 0.991115  ]]
[[0.00135829 0.99864167]]
[[0.00141111 0.99858886]]
[[0.00313035 0.9968696 ]]
[[0.00430434 0.9956956 ]]
[[0.04170568 0.9582944 ]]
[[0.0054988  0.99450123]]
[[0.00198739 0.99801254]]
[[0.03597823 0.96402174]]
[[0.0019069  0.99809307]]
[[0.01376853 0.9862315 ]]
[[0.00705766 0.99294233]]
[[0.01878629 0.9812137 ]]
[[0.02192669 0.9780733 ]]
[[0.924213   0.07578701]]
[[0.00450154 0.99549854]]
[[0.01074548 0.9892545 ]]
[[0.00929065 0.9907094 ]]
[[0.09479126 0.9052087 ]]
[[0.00119541 0.99880457]]
[[0.00130786 0.9986922 ]]
[[0.01128931 0.9887107 ]]
[[0.00862796 0.9913721 ]]
[[0.01660281 0.9833972 ]]
[[0.00144386 0.9985562 ]]
[[0.03163849 0.96836156]]
[[0.00890547 0.9910945 ]]
[[0.00112398 0.99887604]]
[[0.00586863 0.9941314 ]]
[[0.00533724 0.99466276]]
[[0.001936

[[0.00238198 0.997618  ]]
[[0.00808137 0.9919186 ]]
[[0.01279258 0.98720735]]
[[0.00563889 0.99436104]]
[[0.03536816 0.9646318 ]]
[[0.00670768 0.99329233]]
[[0.01132876 0.9886713 ]]
[[0.02267565 0.9773243 ]]
[[0.00219167 0.9978084 ]]
[[0.00824868 0.9917514 ]]
[[0.00201289 0.99798715]]
[[0.00191571 0.9980843 ]]
[[0.11005654 0.8899435 ]]
[[0.01982843 0.98017156]]
[[0.00434835 0.99565166]]
[[0.02600842 0.97399163]]
[[0.08327263 0.91672736]]
[[0.35062185 0.6493782 ]]
[[0.00776942 0.9922306 ]]
[[0.04351987 0.95648015]]
[[0.02052347 0.9794765 ]]
[[0.00233003 0.99767   ]]
[[0.01395971 0.98604035]]
[[0.00772975 0.99227023]]
[[0.02088316 0.97911686]]
[[0.00331224 0.9966878 ]]
[[0.00699779 0.99300224]]
[[0.06553128 0.93446875]]
[[0.01365829 0.98634166]]
[[0.00216608 0.9978339 ]]
[[0.0773844 0.9226156]]
[[0.00241173 0.9975883 ]]
[[0.00114468 0.99885535]]
[[0.00627679 0.9937232 ]]
[[0.00293822 0.9970618 ]]
[[0.02001535 0.97998464]]
[[0.0013662 0.9986338]]
[[0.00224707 0.99775296]]
[[0.00289305 0.9

[[0.00422196 0.99577796]]
[[0.01215567 0.98784435]]
[[0.00313452 0.99686545]]
[[0.03213993 0.9678601 ]]
[[0.00384373 0.9961563 ]]
[[0.0026704 0.9973296]]
[[0.16616893 0.8338311 ]]
[[0.0018946 0.9981054]]
[[0.04073082 0.9592692 ]]
[[0.00977174 0.9902283 ]]
[[0.00321693 0.996783  ]]
[[0.0010627 0.9989373]]
[[0.00316629 0.99683374]]
[[0.07104314 0.92895687]]
[[0.09433744 0.90566254]]
[[0.00175278 0.99824727]]
[[0.3040492 0.6959508]]
[[0.00232385 0.9976762 ]]
[[0.00789378 0.9921062 ]]
[[0.00369134 0.9963086 ]]
[[0.06075473 0.9392453 ]]
[[0.00146665 0.99853337]]
[[0.01126507 0.9887349 ]]
[[0.00235416 0.9976458 ]]
[[0.10668252 0.8933174 ]]
[[0.0038518 0.9961482]]
[[0.00121858 0.9987814 ]]
[[0.00644908 0.9935509 ]]
[[0.00117326 0.9988267 ]]
[[0.00103518 0.9989648 ]]
[[0.020018 0.979982]]
[[0.03746236 0.96253765]]
[[0.02151326 0.9784868 ]]
[[0.00924788 0.9907521 ]]
[[0.01587888 0.9841211 ]]
[[0.01414153 0.9858585 ]]
[[0.07290134 0.92709863]]
[[0.00343175 0.9965682 ]]
[[0.05221112 0.94778883]]


[[0.00395823 0.9960418 ]]
[[0.00149761 0.9985024 ]]
[[0.00812905 0.991871  ]]
[[0.00515465 0.9948454 ]]
[[0.02526469 0.9747353 ]]
[[0.0010473 0.9989526]]
[[0.00500016 0.9949999 ]]
[[0.06320532 0.9367947 ]]
[[0.00758803 0.9924119 ]]
[[0.00700592 0.992994  ]]
[[0.00140149 0.9985985 ]]
[[0.00154201 0.998458  ]]
[[0.10246111 0.89753896]]
[[0.00301367 0.9969863 ]]
[[0.00332155 0.9966785 ]]
[[0.23117366 0.7688263 ]]
[[0.00270333 0.99729663]]
[[0.00324427 0.99675566]]
[[0.00462263 0.9953773 ]]
[[0.06037986 0.93962014]]
[[0.0735049 0.9264951]]
[[0.00300371 0.9969963 ]]
[[0.02904901 0.970951  ]]
[[0.0773844 0.9226156]]
[[0.06320532 0.9367947 ]]
[[0.00100681 0.9989932 ]]
[[0.01710675 0.9828933 ]]
[[0.04163074 0.95836926]]
[[0.00423096 0.995769  ]]
[[0.0055417 0.9944583]]
[[0.0017364  0.99826366]]
[[0.00247496 0.99752504]]
[[0.00319024 0.9968098 ]]
[[0.00450154 0.99549854]]
[[0.00202357 0.9979765 ]]
[[0.00112408 0.9988759 ]]
[[0.03479351 0.9652065 ]]
[[0.02541667 0.9745833 ]]
[[0.00156893 0.99843

[[0.00690383 0.9930962 ]]
[[0.00276184 0.99723816]]
[[0.00161295 0.9983871 ]]
[[0.0027528  0.99724716]]
[[0.00160675 0.99839324]]
[[0.00119748 0.99880254]]
[[0.0053641 0.9946359]]
[[0.00549426 0.9945057 ]]
[[0.00134042 0.9986596 ]]
[[0.00165848 0.99834156]]
[[0.1196837 0.8803163]]
[[0.23311974 0.7668803 ]]
[[0.00231306 0.997687  ]]
[[0.00451776 0.9954822 ]]
[[0.08449116 0.91550887]]
[[0.01098077 0.9890192 ]]
[[0.0032505 0.9967495]]
[[0.00141974 0.9985802 ]]
[[0.00130441 0.99869555]]
[[0.00314644 0.99685353]]
[[0.00715478 0.99284524]]
[[0.06896115 0.93103886]]
[[0.00180052 0.99819946]]
[[0.00313218 0.99686784]]
[[0.30189812 0.6981018 ]]
[[0.00109132 0.99890864]]
[[0.00164571 0.9983543 ]]
[[0.01037586 0.9896241 ]]
[[0.00201828 0.99798167]]
[[0.00269812 0.9973018 ]]
[[0.00107257 0.9989274 ]]
[[0.00196537 0.99803466]]
[[0.00326346 0.9967366 ]]
[[0.06934069 0.93065923]]
[[0.02031841 0.9796816 ]]
[[0.00157954 0.9984205 ]]
[[0.03761939 0.96238065]]
[[0.00195078 0.99804926]]
[[0.00299646 0.997

[[0.00134232 0.9986577 ]]
[[0.00645234 0.9935476 ]]
[[0.00243765 0.9975624 ]]
[[0.10526177 0.89473826]]
[[0.00207452 0.9979255 ]]
[[0.03851258 0.9614875 ]]
[[0.00569004 0.9943099 ]]
[[0.00197114 0.9980288 ]]
[[0.0015258 0.9984742]]
[[0.00204734 0.9979526 ]]
[[0.02017292 0.97982705]]
[[6.752438e-04 9.993248e-01]]
[[0.00305111 0.9969489 ]]
[[0.00286847 0.99713147]]
[[0.01238548 0.9876145 ]]
[[0.00125275 0.9987472 ]]
[[0.00180669 0.9981933 ]]
[[0.00152341 0.99847656]]
[[0.03679726 0.9632028 ]]
[[0.00195907 0.998041  ]]
[[0.00774358 0.9922564 ]]
[[0.01747082 0.98252916]]
[[0.01542794 0.98457205]]
[[0.01360968 0.98639035]]
[[0.00139769 0.99860233]]
[[0.00424936 0.99575067]]
[[0.00704911 0.9929509 ]]
[[0.0010818 0.9989182]]
[[0.00410641 0.9958936 ]]
[[0.00251511 0.9974849 ]]
[[0.0307009 0.9692991]]
[[0.0022044 0.9977956]]
[[0.02318054 0.97681946]]
[[0.02758934 0.97241074]]
[[0.0211532 0.9788467]]
[[0.00158756 0.9984124 ]]
[[9.4549113e-04 9.9905449e-01]]
[[0.00377928 0.99622077]]
[[0.00110488

[[0.0056454 0.9943546]]
[[0.00469149 0.99530846]]
[[0.002487   0.99751294]]
[[0.00664449 0.9933555 ]]
[[0.00143752 0.9985625 ]]
[[0.00724769 0.9927523 ]]
[[0.0188649  0.98113513]]
[[0.02723842 0.97276163]]
[[0.00305707 0.99694294]]
[[0.0131299 0.9868701]]
[[0.00208785 0.9979121 ]]
[[0.02428326 0.97571677]]
[[0.00607554 0.99392444]]
[[0.01361175 0.98638827]]
[[0.0089075 0.9910925]]
[[0.00774443 0.99225557]]
[[0.00634843 0.9936515 ]]
[[0.01548371 0.98451626]]
[[0.00306752 0.9969325 ]]
[[0.0126784  0.98732156]]
[[0.0588778 0.9411222]]
[[0.01380213 0.9861979 ]]
[[0.0033318  0.99666816]]
[[0.00278121 0.9972187 ]]
[[0.00146289 0.99853706]]
[[0.00187724 0.99812275]]
[[0.16276456 0.8372354 ]]
[[0.03077697 0.969223  ]]
[[0.02347741 0.97652256]]
[[0.00446236 0.99553764]]
[[0.00214904 0.997851  ]]
[[0.01271065 0.98728937]]
[[0.00379578 0.9962042 ]]
[[0.00483785 0.9951622 ]]
[[0.00227129 0.99772877]]
[[0.00337092 0.99662906]]
[[0.00121927 0.9987808 ]]
[[0.00200808 0.9979919 ]]
[[0.00254305 0.99745

[[0.00116027 0.9988398 ]]
[[0.00304506 0.9969549 ]]
[[0.00126209 0.9987379 ]]
[[0.02839096 0.971609  ]]
[[0.00184025 0.9981597 ]]
[[0.12520896 0.874791  ]]
[[0.09150587 0.9084942 ]]
[[9.319454e-04 9.990681e-01]]
[[0.0011662  0.99883384]]
[[0.00498835 0.9950117 ]]
[[0.01638383 0.9836162 ]]
[[0.03176397 0.968236  ]]
[[0.01546525 0.98453474]]
[[0.00310292 0.9968971 ]]
[[0.00777885 0.9922212 ]]
[[0.13331717 0.86668277]]
[[0.00457376 0.99542624]]
[[0.00123149 0.9987685 ]]
[[0.06242131 0.9375786 ]]
[[0.00258991 0.9974101 ]]
[[0.00145742 0.99854255]]
[[0.00782257 0.9921774 ]]
[[0.01133845 0.9886615 ]]
[[0.00205122 0.9979488 ]]
[[0.00741664 0.9925834 ]]
[[9.0726605e-04 9.9909270e-01]]
[[0.00200252 0.99799746]]
[[0.00262449 0.9973755 ]]
[[0.07241824 0.9275818 ]]
[[0.00220597 0.99779403]]
[[0.0024585  0.99754155]]
[[0.0773844 0.9226156]]
[[0.01493593 0.9850641 ]]
[[0.0010355  0.99896455]]
[[0.00193137 0.99806863]]
[[0.00531317 0.99468684]]
[[0.00102082 0.9989792 ]]
[[0.00272442 0.99727565]]
[[0.

[[0.00253262 0.9974674 ]]
[[0.00118661 0.9988134 ]]
[[0.00266988 0.99733007]]
[[0.00689749 0.99310255]]
[[0.01106678 0.9889332 ]]
[[0.02980865 0.97019136]]
[[0.01035901 0.989641  ]]
[[0.00161216 0.9983878 ]]
[[0.0020881 0.9979119]]
[[0.45833972 0.54166025]]
[[0.00419806 0.995802  ]]
[[0.06401177 0.9359882 ]]
[[0.00778428 0.9922157 ]]
[[0.00677697 0.9932231 ]]
[[0.00323609 0.99676394]]
[[0.16751875 0.83248127]]
[[0.00134367 0.9986563 ]]
[[0.00949346 0.9905066 ]]
[[0.00121667 0.9987833 ]]
[[0.00209121 0.99790883]]
[[0.00171206 0.998288  ]]
[[0.00187943 0.9981206 ]]
[[0.02656449 0.9734355 ]]
[[0.05504216 0.94495785]]
[[0.01466802 0.98533195]]
[[0.00225245 0.9977475 ]]
[[0.00291918 0.99708074]]
[[0.08560549 0.91439456]]
[[0.00203201 0.997968  ]]
[[0.00260593 0.9973941 ]]
[[0.00450154 0.99549854]]
[[0.00562121 0.99437875]]
[[0.00887146 0.99112856]]
[[0.00981009 0.99018997]]
[[0.00245174 0.9975483 ]]
[[0.04724896 0.95275104]]
[[0.03239117 0.9676088 ]]
[[0.00445848 0.9955415 ]]
[[0.01246584 0

[[0.00768248 0.99231756]]
[[0.05405504 0.94594496]]
[[0.00167191 0.99832815]]
[[0.00178743 0.9982126 ]]
[[0.0017315 0.9982685]]
[[0.00113174 0.99886835]]
[[9.0071524e-04 9.9909925e-01]]
[[0.02727936 0.9727207 ]]
[[0.00499704 0.9950029 ]]
[[0.00135869 0.9986413 ]]
[[0.0023908  0.99760914]]
[[0.00251683 0.9974832 ]]
[[0.00591257 0.99408746]]
[[0.01358879 0.9864113 ]]
[[0.00324099 0.996759  ]]
[[0.02878096 0.971219  ]]
[[0.12312926 0.87687075]]
[[0.01941244 0.9805876 ]]
[[0.00127895 0.99872106]]
[[0.00596393 0.9940361 ]]
[[0.15280111 0.8471989 ]]
[[0.00113784 0.99886215]]
[[0.00230768 0.99769235]]
[[0.00155004 0.9984499 ]]
[[9.898880e-04 9.990101e-01]]
[[0.0024064 0.9975936]]
[[0.02515193 0.9748481 ]]
[[0.15026191 0.8497381 ]]
[[8.672614e-04 9.991328e-01]]
[[9.0695929e-04 9.9909306e-01]]
[[0.02452248 0.9754775 ]]
[[0.07137071 0.9286293 ]]
[[0.00139523 0.99860483]]
[[0.04222997 0.95777005]]
[[0.03595366 0.96404636]]
[[0.00256658 0.9974335 ]]
[[0.00244363 0.9975563 ]]
[[0.00165679 0.9983432

[[0.0011556 0.9988444]]
[[0.07545102 0.9245489 ]]
[[0.00140388 0.99859613]]
[[0.00498224 0.9950178 ]]
[[0.00289541 0.9971046 ]]
[[0.00158662 0.9984133 ]]
[[0.00706981 0.99293023]]
[[0.00905686 0.99094313]]
[[0.12434848 0.8756515 ]]
[[0.00360321 0.99639684]]
[[0.00103926 0.99896073]]
[[0.03995524 0.96004474]]
[[0.00370101 0.99629897]]
[[0.00164751 0.9983525 ]]
[[0.03110417 0.96889585]]
[[0.00220835 0.99779165]]
[[0.00156582 0.9984341 ]]
[[0.01064742 0.9893526 ]]
[[0.00384257 0.99615747]]
[[0.00112592 0.998874  ]]
[[0.03071984 0.9692802 ]]
[[0.00182348 0.9981766 ]]
[[0.00181529 0.99818474]]
[[0.00149095 0.998509  ]]
[[0.0133062 0.9866938]]
[[0.0524817 0.9475183]]
[[0.00131106 0.998689  ]]
[[0.00135456 0.9986455 ]]
[[0.04433094 0.9556691 ]]
[[0.10833492 0.89166504]]
[[0.00555066 0.9944494 ]]
[[0.00251208 0.9974879 ]]
[[0.00141749 0.9985825 ]]
[[0.00105864 0.99894136]]
[[0.05820887 0.9417911 ]]
[[0.00823974 0.9917603 ]]
[[0.00133627 0.9986638 ]]
[[0.00153333 0.99846673]]
[[0.00479202 0.995

[[9.631596e-04 9.990369e-01]]
[[0.21503285 0.7849671 ]]
[[0.00397586 0.99602413]]
[[0.00785842 0.9921416 ]]
[[0.17050202 0.82949793]]
[[0.007211 0.992789]]
[[0.01015234 0.9898477 ]]
[[0.00376757 0.99623245]]
[[0.07608488 0.92391515]]
[[0.00197424 0.9980258 ]]
[[0.13224727 0.86775273]]
[[0.00332084 0.9966792 ]]
[[0.01559358 0.9844065 ]]
[[0.00159347 0.9984066 ]]
[[0.0128138 0.9871862]]
[[0.00362133 0.9963787 ]]
[[0.01163411 0.9883659 ]]
[[0.00252379 0.99747616]]
[[0.00353467 0.9964653 ]]
[[0.00195296 0.998047  ]]
[[0.14330615 0.8566938 ]]
[[0.00147966 0.9985203 ]]
[[0.00936801 0.99063194]]
[[0.03677257 0.96322745]]
[[0.00113182 0.9988682 ]]
[[0.07614797 0.923852  ]]
[[0.01465503 0.98534495]]
[[0.00341956 0.9965804 ]]
[[0.00247077 0.9975292 ]]
[[0.12313985 0.87686014]]
[[0.00122996 0.99877006]]
[[0.00234767 0.99765235]]
[[0.00431829 0.99568164]]
[[0.00138467 0.99861526]]
[[0.00150463 0.99849534]]
[[0.00269626 0.9973037 ]]
[[0.00145875 0.99854124]]
[[0.00208272 0.99791723]]
[[0.00235704 0

[[0.00450154 0.99549854]]
[[0.01113232 0.9888677 ]]
[[0.00415442 0.9958456 ]]
[[0.00855284 0.9914472 ]]
[[0.01273792 0.98726207]]
[[0.00273473 0.99726534]]
[[0.11387106 0.88612896]]
[[0.00339501 0.99660504]]
[[0.00110981 0.9988902 ]]
[[0.01580059 0.9841994 ]]
[[0.00250906 0.997491  ]]
[[0.025095 0.974905]]
[[9.534327e-04 9.990465e-01]]
[[0.04476926 0.9552307 ]]
[[0.00268692 0.9973131 ]]
[[0.00113754 0.9988625 ]]
[[0.00401626 0.9959837 ]]
[[0.00118766 0.9988123 ]]
[[0.00190303 0.998097  ]]
[[0.00388014 0.99611986]]
[[0.00528562 0.9947143 ]]
[[8.7690749e-04 9.9912316e-01]]
[[0.00116251 0.99883753]]
[[0.11956609 0.8804339 ]]
[[0.00669707 0.99330294]]
[[0.00372417 0.9962759 ]]
[[0.02159717 0.97840285]]
[[0.00237521 0.9976248 ]]
[[0.03267519 0.96732485]]
[[0.00274073 0.99725926]]
[[0.00364028 0.99635977]]
[[0.00150326 0.9984968 ]]
[[0.00106865 0.99893135]]
[[0.00100402 0.99899596]]
[[0.00811282 0.99188715]]
[[0.00178574 0.99821424]]
[[0.04339123 0.95660883]]
[[0.00225621 0.99774384]]
[[0.00

[[0.00617737 0.9938226 ]]
[[0.00101674 0.9989832 ]]
[[0.01801109 0.9819889 ]]
[[0.03370722 0.9662928 ]]
[[0.056191 0.943809]]
[[0.00666829 0.99333173]]
[[0.00239205 0.99760795]]
[[0.00341076 0.9965893 ]]
[[0.00176538 0.9982346 ]]
[[0.00189821 0.9981018 ]]
[[0.0067993 0.9932007]]
[[0.01025766 0.9897424 ]]
[[0.0051427 0.9948573]]
[[0.00399046 0.99600947]]
[[0.007663   0.99233705]]
[[0.06587974 0.93412024]]
[[0.0298386 0.9701614]]
[[0.00317593 0.996824  ]]
[[0.00204557 0.99795437]]
[[0.00107625 0.9989237 ]]
[[0.00349961 0.9965004 ]]
[[0.00573746 0.9942625 ]]
[[0.00691574 0.9930843 ]]
[[0.00154406 0.9984559 ]]
[[0.00321182 0.99678814]]
[[0.01470531 0.9852947 ]]
[[0.00105215 0.9989479 ]]
[[0.03012499 0.969875  ]]
[[0.00689989 0.99310005]]
[[0.00621016 0.99378985]]
[[0.00658295 0.993417  ]]
[[0.00133808 0.9986619 ]]
[[0.00335934 0.9966407 ]]
[[0.13126004 0.86873996]]
[[0.00221962 0.9977804 ]]
[[0.06301439 0.9369856 ]]
[[0.05122607 0.94877386]]
[[0.0080045 0.9919956]]
[[0.00253714 0.99746287]

[[0.00161133 0.99838865]]
[[0.0232838  0.97671616]]
[[0.02669491 0.9733051 ]]
[[0.00150896 0.99849105]]
[[0.00499335 0.9950067 ]]
[[0.01999979 0.98000026]]
[[0.00505179 0.99494815]]
[[0.00927943 0.9907205 ]]
[[0.00985036 0.9901496 ]]
[[0.02399887 0.97600114]]
[[0.00168156 0.99831843]]
[[0.00326015 0.9967398 ]]
[[0.0014768 0.9985232]]
[[0.01777595 0.98222405]]
[[0.04432773 0.95567226]]
[[0.02219811 0.97780186]]
[[0.0037407  0.99625933]]
[[0.12578763 0.8742124 ]]
[[0.09688276 0.90311724]]
[[0.00141478 0.9985852 ]]
[[0.00162735 0.99837273]]
[[0.00338804 0.9966119 ]]
[[0.07593739 0.9240626 ]]
[[0.00319039 0.99680954]]
[[0.00173311 0.9982668 ]]
[[9.9238614e-04 9.9900764e-01]]
[[0.00384314 0.9961569 ]]
[[0.00336312 0.99663687]]
[[0.03245607 0.96754396]]
[[0.00769773 0.9923023 ]]
[[0.00391388 0.9960861 ]]
[[0.00273333 0.99726665]]
[[0.0020441 0.9979559]]
[[8.1158202e-04 9.9918836e-01]]
[[0.00236902 0.99763095]]
[[0.08229542 0.9177046 ]]
[[0.00572755 0.9942725 ]]
[[0.004568 0.995432]]
[[0.0011

[[0.01345857 0.9865414 ]]
[[0.00775244 0.9922476 ]]
[[0.00734762 0.9926523 ]]
[[0.00109037 0.9989096 ]]
[[0.00646599 0.99353397]]
[[0.00698948 0.99301046]]
[[0.00324704 0.9967529 ]]
[[0.00161682 0.99838316]]
[[0.00195865 0.9980413 ]]
[[9.85980e-04 9.99014e-01]]
[[0.01089109 0.9891089 ]]
[[0.00168603 0.998314  ]]
[[0.00639218 0.9936079 ]]
[[0.00159092 0.9984091 ]]
[[0.00316288 0.99683714]]
[[0.00175755 0.9982425 ]]
[[8.4715727e-04 9.9915290e-01]]
[[0.00700301 0.992997  ]]
[[0.11806035 0.88193965]]
[[0.00390562 0.9960944 ]]
[[0.00308572 0.99691427]]
[[0.00567779 0.9943222 ]]
[[0.00435025 0.99564976]]
[[0.00347695 0.996523  ]]
[[0.0056001  0.99439985]]
[[0.01441955 0.9855804 ]]
[[0.00651417 0.99348587]]
[[0.01540442 0.9845956 ]]
[[0.01439611 0.9856039 ]]
[[0.00488064 0.99511933]]
[[0.00832621 0.99167377]]
[[0.0019159  0.99808407]]
[[0.00659239 0.9934076 ]]
[[0.08012526 0.9198747 ]]
[[0.0270731 0.9729269]]
[[0.00344904 0.9965509 ]]
[[0.00148883 0.99851114]]
[[0.00121365 0.9987864 ]]
[[0.05

[[0.00273246 0.9972676 ]]
[[0.00432617 0.99567384]]
[[0.00562093 0.9943791 ]]
[[0.00235358 0.9976464 ]]
[[0.00456483 0.9954352 ]]
[[0.3299202  0.67007977]]
[[0.0090998  0.99090016]]
[[0.00318407 0.996816  ]]
[[0.00725235 0.9927476 ]]
[[0.05977474 0.94022524]]
[[0.00130396 0.998696  ]]
[[0.00127021 0.99872977]]
[[0.05265972 0.94734025]]
[[0.14500932 0.8549907 ]]
[[0.00714896 0.992851  ]]
[[0.00662427 0.9933757 ]]
[[0.00384845 0.9961515 ]]
[[0.00294024 0.99705976]]
[[0.00239292 0.9976071 ]]
[[0.00241579 0.9975842 ]]
[[0.00168646 0.99831355]]
[[0.00314509 0.9968549 ]]
[[8.815167e-04 9.991185e-01]]
[[0.02755207 0.97244793]]
[[0.00627336 0.9937266 ]]
[[0.00112914 0.9988708 ]]
[[0.01119402 0.988806  ]]
[[0.00185568 0.99814427]]
[[0.00228891 0.99771106]]
[[0.00244472 0.9975553 ]]
[[0.00106378 0.99893624]]
[[0.03022811 0.96977186]]
[[0.00667467 0.99332535]]
[[0.00111398 0.99888605]]
[[0.06563982 0.93436015]]
[[0.00437537 0.9956246 ]]
[[0.03626234 0.96373767]]
[[0.00774886 0.9922511 ]]
[[8.5335

In [23]:
preds

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [37]:
with open('out/prediction_2.csv', 'w') as f:
    f.write('Id,Prediction'+'\n')
    for i,p in zip(test_ids, preds):
        if str(p) == "0":
            p = "-1"
        f.write(i+','+str(p)+'\n')

In [22]:
preds_ok = [-1 if x == 0 else None for x in preds]
print(keras.metrics.accuracy(test_y, preds_ok))

ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.